# Variaveis onde alteração são necessárias

BOARD_TAG=uno # Placa arduino utilizada no projeto
#PORT = /dev/ttyUSBx # Formato Usual: /dev/ttyUSBx onde x é a port USB serial onde seu arduino está inserido

include /usr/share/arduino/Arduino.mk
